project_id = "hzuigirxuucwtwmdvjod"

[functions.agent-chat]
verify_jwt = false

[functions.ingest-knowledge]
verify_jwt = false

[functions.get-conversation]
verify_jwt = false

[functions.create-paypal-subscription]
verify_jwt = false

[functions.create-paypal-portal]
verify_jwt = false

[functions.cancel-paypal-subscription]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.auto-research]
verify_jwt = false

[functions.auto-create-agent]
verify_jwt = false

[functions.manage-provider]
verify_jwt = false

